services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  deligator:
    build: Deligator/.
    image: ethantrippedwards/atlas-assessment:deligator
    networks:
      - rabbit
    volumes:
      - data_store:/data
    deploy:
      mode: global-job
    depends_on:
      - rabbitmq
  worker:
    build: worker/.
    image: ethantrippedwards/atlas-assessment:worker
    networks:
      - rabbit
    deploy:
      mode: replicated-job
      replicas: 5
    depends_on:
      - rabbitmq

networks:
  rabbit:
    driver: overlay
    attachable: true
volumes:
  data_store:
